[project]
name = "my-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
]

[tool.uv.sources]
requests = { path = "../../../Users/marat/Downloads/requests-2.32.3-py3-none-any.whl" }
